/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter */

#ifndef _Included_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
#define _Included_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    openQuery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_openQuery
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    addCounter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_addCounter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    updateHandles
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_updateHandles
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    collectQueryData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_collectQueryData
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueSysCPUSys
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueSysCPUSys
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueSysCPUUser
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueSysCPUUser
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getMemoryTotal
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getMemoryTotal
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueMemAvailable
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueMemAvailable
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValuePageFileUsage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValuePageFileUsage
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValuePageFileBytes
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValuePageFileBytes
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueVirtualBytes
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueVirtualBytes
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueSystemFDs
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueSystemFDs
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValuePageIn
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValuePageIn
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValuePageOut
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValuePageOut
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueProcessUserTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueProcessUserTime
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueProcessPrivilegedTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueProcessPrivilegedTime
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueMajFlt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueMajFlt
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueVSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueVSize
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueRSS
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueRSS
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueNumThreads
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueNumThreads
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    getFormattedCounterValueProcFDs
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_getFormattedCounterValueProcFDs
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter
 * Method:    closeQuery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_PerfCounter_closeQuery
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
