/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader */

#ifndef _Included_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
#define _Included_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    openQuery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_openQuery
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    collectQueryData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_collectQueryData
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemCPUSys
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemCPUSys
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemCPUUser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemCPUUser
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemCPUTotal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemCPUTotal
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemMemoryFree
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemMemoryFree
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemMemoryTotal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemMemoryTotal
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemSwapFree
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemSwapFree
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemSwapTotal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemSwapTotal
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemPageIn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemPageIn
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getSystemPageOut
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getSystemPageOut
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getProcessCPUUser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getProcessCPUUser
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getProcessCPUSys
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getProcessCPUSys
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getProcessMajFlt
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getProcessMajFlt
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getProcessMemoryVirtual
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getProcessMemoryVirtual
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getProcessMemoryPhysical
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getProcessMemoryPhysical
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    getNumThreads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_getNumThreads
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader
 * Method:    closeQuery
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_co_acroquest_endosnipe_javelin_resource_proc_SolarisResourceReader_closeQuery
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
